# Generated by Django 5.1.6 on 2025-05-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="animal_images/")),
            ],
        ),
    ]
