# Generated by Django 5.1.6 on 2025-05-12 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0009_petfood_delete_dogrecipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="petfood",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_petfoods", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
