# Generated by Django 5.1.6 on 2025-05-14 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0011_alter_animal_gender_alter_missinganimal_gender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "건강 관리"),
                    ("training", "훈련 팁"),
                    ("tips", "팁 & 조언"),
                    ("community", "커뮤니티"),
                    ("events", "이벤트"),
                    ("daily", "일상 공유"),
                    ("food", "반려동물 음식"),
                    ("funny", "웃긴 순간들"),
                    ("travel", "여행과 외출"),
                    ("question", "질문 있어요"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PetFoodRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="추천 제목")),
                ("description", models.TextField(verbose_name="설명")),
                (
                    "food_type",
                    models.CharField(
                        choices=[("raw", "생식"), ("snack", "간식"), ("meal", "식사")],
                        default="raw",
                        max_length=20,
                        verbose_name="음식 유형",
                    ),
                ),
                (
                    "suitable_for",
                    models.CharField(
                        help_text="예: 강아지, 고양이 등",
                        max_length=100,
                        verbose_name="적합한 동물",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="pet_food_recommendations/",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추천일"),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="추천자",
                    ),
                ),
            ],
        ),
    ]
