# Generated by Django 5.1.6 on 2025-05-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("수컷", "수컷"), ("암컷", "암컷"), ("기타", "기타")],
                default="기타",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="personality",
            field=models.TextField(blank=True),
        ),
    ]
