# Generated by Django 5.1.6 on 2025-05-08 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_animal_gender_animal_personality"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="animal",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="animal",
            name="neutered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="vaccinated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("수컷", "수컷"), ("암컷", "암컷"), ("믹스", "믹스")],
                default="믹스",
                max_length=10,
            ),
        ),
    ]
