# Generated by Django 5.1.6 on 2025-05-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0003_animal_breed_animal_created_at_animal_neutered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, default="믹스", max_length=100),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("수컷", "수컷"), ("암컷", "암컷"), ("믹스", "믹스")],
                default="수컷",
                max_length=10,
            ),
        ),
    ]
