# Generated by Django 5.1.6 on 2025-05-08 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0004_alter_animal_breed_alter_animal_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_animals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="animal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("수컷", "수컷"), ("암컷", "암컷"), ("믹스", "믹스")],
                default="믹스",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pet.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
