# Generated by Django 5.1.6 on 2025-05-09 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0005_animal_likes_animal_location_alter_animal_breed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="animal",
        ),
        migrations.CreateModel(
            name="MissingAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("수컷", "수컷"), ("암컷", "암컷"), ("믹스", "믹스")],
                        default="믹스",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="missing_animals/")),
                ("location", models.CharField(max_length=255)),
                ("date_missing", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "건강 관리"),
                            ("training", "훈련 팁"),
                            ("adoption", "입양"),
                            ("lost", "실종 동물"),
                            ("tips", "팁 & 조언"),
                            ("community", "커뮤니티"),
                            ("events", "이벤트"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="pet.post",
            ),
            preserve_default=False,
        ),
    ]
