# Generated by Django 5.1.6 on 2025-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0008_dogrecipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="요리 제목")),
                ("ingredients", models.TextField(verbose_name="재료")),
                ("instructions", models.TextField(verbose_name="조리 방법")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="pet_foods/", verbose_name="이미지"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DogRecipe",
        ),
    ]
