# Generated by Django 5.1.6 on 2025-05-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0010_petfood_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("수컷", "수컷"), ("암컷", "암컷")],
                default="암컷",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="missinganimal",
            name="gender",
            field=models.CharField(
                choices=[("수컷", "수컷"), ("암컷", "암컷")],
                default="암컷",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "건강 관리"),
                    ("training", "훈련 팁"),
                    ("tips", "팁 & 조언"),
                    ("community", "커뮤니티"),
                    ("events", "이벤트"),
                    ("daily", "일상 공유"),
                    ("food", "반려동물 음식"),
                    ("funny", "웃긴 순간들"),
                    ("travel", "여행과 외출"),
                    ("question", "질문 있어요"),
                    ("supplements", "건강식품 추천"),
                    ("toys", "장난감 추천"),
                    ("indoor", "실내용 추천"),
                    ("outdoor", "야외활동 추천"),
                    ("elderly", "노령 동물 케어"),
                    ("multi_pet", "다마리 가족"),
                    ("seasonal", "계절별 추천"),
                ],
                max_length=20,
            ),
        ),
    ]
